import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

// ── Translations (ported from lang.js) ───────────────────────────────────────

const TRANSLATIONS: Record<string, Record<string, string>> = {
  zh: {
    brandTagline: '每一杯<br>都是故事',
    brandSub: '精心烘焙，用心服务',
    loginWelcome: '欢迎回来',
    loginSubtitle: '请选择账号类型并登录',
    roleAdmin: '管理员',
    roleStaff: '员工',
    labelUsername: '用户名',
    labelPassword: '密码',
    phUsername: '请输入用户名',
    phPassword: '请输入密码',
    btnLogin: '登录',
    signingIn: '登录成功...',
    demoAccount: '演示账号',
    hintBoss: '用户名：<strong>boss</strong>&ensp;密码：<strong>boss123</strong>',
    hintStaff: '用户名：<strong>staff001</strong>&ensp;密码：<strong>staff123</strong>',
    errFillAll: '请填写用户名和密码',
    errWrongCreds: '用户名或密码错误，请重试',
    callStaff: '呼叫服务员',
    tableLabel: '桌号',
    todayMenu: '今日菜单',
    menuSubtitle: '选好后点「查看订单」提交，我们马上为您准备 ☕',
    viewOrder: '查看订单',
    tapToView: '点击查看订单',
    myOrder: '我的订单',
    total: '合计',
    submitOrder: '提交订单',
    submitting: '提交中...',
    orderSuccess: '订单已提交！',
    orderSuccessSub: '我们正在为您准备\n请稍候，感谢惠顾',
    emptyCart: '还没有选择商品\n返回菜单加入吧',
    soldOut: '售罄',
    itemNowSoldOut: '「{0}」已售罄，已从您的购物车移除',
    callSent: '✅ 已通知服务员，请稍候',
    callDuplicate: '⏳ 已发送呼叫，服务员正在赶来',
    noTableHeader: '欢迎光临',
    noTableSub: '请扫描桌面上的二维码查看菜单',
    noTableTitle: '未识别到桌号',
    noTableBody: '请扫描您桌上的专属二维码\n即可浏览菜单并点单',
    signOut: '退出登录',
    tablesCalling: '桌呼叫中',
    customerCalls: '📢 客户呼叫中',
    orderMgmt: '订单管理',
    lastUpdated: '最后更新',
    autoRefresh: '每 3 秒自动刷新',
    pending: '待处理',
    completed: '已完成',
    tableNum: '桌号',
    cancelOrder: '取消订单',
    checkout: '结账收款',
    checkoutTitle: '结账收款',
    amountDue: '应收金额',
    confirmPayment: '确认已收款 ✓',
    cancel: '取消',
    confirmCancelTitle: '确认取消订单？',
    confirmCancelMsg: '桌号 {0} 的订单将被取消，此操作不可撤销。',
    back: '返回',
    confirmCancel: '确认取消',
    noPending: '暂无待处理订单',
    noCompleted: '今日暂无完成订单',
    toastPayment: '✅ 收款成功',
    toastCancelled: '订单已取消',
    toastNewOrder: '🔔 新订单 +{0}',
    toastNewCall: '📢 有顾客呼叫服务员',
    toastDismissed: '✅ 已标记处理',
    statusPaid: '✓ 已结账',
    statusCancelled: '✕ 已取消',
    eachUnit: '¥{0} / 杯',
    dashTitle: '管理后台',
    menuMgmt: '菜单管理',
    qrCodes: '桌位二维码',
    reports: '报告',
    addItem: '添加新菜品',
    phItemName: '菜品名称，如 Latte',
    phItemCode: '编码，如 C01',
    phItemPrice: '价格（K）',
    addBtn: '添加',
    deleteItem: '删除',
    deleteConfirm: '确认删除「{0}」？此操作不可撤销。',
    baseUrl: '菜单页面地址',
    tableCount: '桌位数量',
    generateQR: '生成二维码',
    downloadQR: '下载',
    downloadAll: '全部下载',
    tableQrLabel: '第 {0} 桌',
    noItems: '菜单为空，请添加菜品',
    loadFailed: '加载失败，请刷新重试',
    toastAdded: '✅ 菜品已添加',
    toastDeleted: '✅ 已删除',
    toastPriceOK: '✅ 价格已更新',
    toastAvailOK: '✅ 状态已更新',
    toastErrAdd: '❌ 添加失败',
    toastErrDel: '❌ 删除失败',
    toastErrPrice: '❌ 价格更新失败',
    toastErrAvail: '❌ 状态更新失败',
    itemName: '菜品名称',
    itemCode: '编码',
    itemPrice: '价格',
    addImage: '添加图片',
    secondsAgo: '{0} 秒前',
    minutesAgo: '{0} 分钟前',
    hoursAgo: '{0} 小时前',
  },

  en: {
    brandTagline: 'Every cup,<br>a story.',
    brandSub: 'Crafted with care, served with heart.',
    loginWelcome: 'Welcome Back',
    loginSubtitle: 'Select your role and sign in',
    roleAdmin: 'Admin',
    roleStaff: 'Staff',
    labelUsername: 'Username',
    labelPassword: 'Password',
    phUsername: 'Enter your username',
    phPassword: 'Enter your password',
    btnLogin: 'Sign In',
    signingIn: 'Signing in...',
    demoAccount: 'Demo Account',
    hintBoss: 'Username: <strong>boss</strong>&ensp;Password: <strong>boss123</strong>',
    hintStaff: 'Username: <strong>staff001</strong>&ensp;Password: <strong>staff123</strong>',
    errFillAll: 'Please fill in username and password',
    errWrongCreds: 'Incorrect username or password, please try again',
    callStaff: 'Call Staff',
    tableLabel: 'Table',
    todayMenu: "Today's Menu",
    menuSubtitle: "Select items, then tap 'View Order' to submit ☕",
    viewOrder: 'View Order',
    tapToView: 'Tap to view order',
    myOrder: 'My Order',
    total: 'Total',
    submitOrder: 'Submit Order',
    submitting: 'Submitting...',
    orderSuccess: 'Order Submitted!',
    orderSuccessSub: "We're preparing your order\nThank you! ☕",
    emptyCart: 'No items selected yet\nGo back and add some!',
    soldOut: 'Sold Out',
    itemNowSoldOut: '"{0}" is now sold out and was removed from your cart',
    callSent: '✅ Staff has been notified, please wait',
    callDuplicate: '⏳ Already notified, staff is on the way',
    noTableHeader: 'Welcome',
    noTableSub: 'Please scan the QR code on your table to view the menu',
    noTableTitle: 'Table Not Found',
    noTableBody: "Please scan your table's QR code\nto browse the menu and order",
    signOut: 'Sign Out',
    tablesCalling: 'table(s) calling',
    customerCalls: '📢 Customer Calls',
    orderMgmt: 'Order Management',
    lastUpdated: 'Last updated',
    autoRefresh: 'Auto refresh every 3s',
    pending: 'Pending',
    completed: 'Completed',
    tableNum: 'Table',
    cancelOrder: 'Cancel',
    checkout: 'Checkout',
    checkoutTitle: 'Checkout',
    amountDue: 'Amount Due',
    confirmPayment: 'Confirm Payment ✓',
    cancel: 'Cancel',
    confirmCancelTitle: 'Cancel Order?',
    confirmCancelMsg: "Table {0}'s order will be cancelled. This cannot be undone.",
    back: 'Back',
    confirmCancel: 'Confirm Cancel',
    noPending: 'No pending orders',
    noCompleted: 'No completed orders today',
    toastPayment: '✅ Payment received',
    toastCancelled: 'Order cancelled',
    toastNewOrder: '🔔 New order +{0}',
    toastNewCall: '📢 Customer calling',
    toastDismissed: '✅ Marked as handled',
    statusPaid: '✓ Paid',
    statusCancelled: '✕ Cancelled',
    eachUnit: 'K{0} each',
    dashTitle: 'Dashboard',
    menuMgmt: 'Menu',
    qrCodes: 'QR Codes',
    reports: 'Reports',
    addItem: 'Add Item',
    phItemName: 'Item name, e.g. Latte',
    phItemCode: 'Code, e.g. C01',
    phItemPrice: 'Price (K)',
    addBtn: 'Add',
    deleteItem: 'Delete',
    deleteConfirm: 'Delete "{0}"? This cannot be undone.',
    baseUrl: 'Menu page URL',
    tableCount: 'Number of tables',
    generateQR: 'Generate QR Codes',
    downloadQR: 'Download',
    downloadAll: 'Download All',
    tableQrLabel: 'Table {0}',
    noItems: 'Menu is empty, add some items',
    loadFailed: 'Load failed, please refresh',
    toastAdded: '✅ Item added',
    toastDeleted: '✅ Deleted',
    toastPriceOK: '✅ Price updated',
    toastAvailOK: '✅ Status updated',
    toastErrAdd: '❌ Failed to add',
    toastErrDel: '❌ Failed to delete',
    toastErrPrice: '❌ Price update failed',
    toastErrAvail: '❌ Status update failed',
    itemName: 'Item Name',
    itemCode: 'Code',
    itemPrice: 'Price',
    addImage: 'Add Image',
    secondsAgo: '{0}s ago',
    minutesAgo: '{0}m ago',
    hoursAgo: '{0}h ago',
  },

  my: {
    brandTagline: 'ဖလားတိုင်း<br>ဇာတ်လမ်းရှိ',
    brandSub: 'ဂရုစိုက်မွမ်းမံ၊ နှလုံးနှင့်ဆောင်ရွက်',
    loginWelcome: 'ကြိုဆိုပါသည်',
    loginSubtitle: 'အကောင့်အမျိုးအစားရွေးပြီး ဝင်ရောက်ပါ',
    roleAdmin: 'မန်နေဂျာ',
    roleStaff: 'ဝန်ထမ်း',
    labelUsername: 'အသုံးပြုသူအမည်',
    labelPassword: 'စကားဝှက်',
    phUsername: 'အသုံးပြုသူအမည်ထည့်ပါ',
    phPassword: 'စကားဝှက်ထည့်ပါ',
    btnLogin: 'ဝင်ရောက်ပါ',
    signingIn: 'ဝင်ရောက်နေသည်...',
    demoAccount: 'စမ်းသပ်အကောင့်',
    hintBoss: 'အမည်: <strong>boss</strong>&ensp;စကားဝှက်: <strong>boss123</strong>',
    hintStaff: 'အမည်: <strong>staff001</strong>&ensp;စကားဝှက်: <strong>staff123</strong>',
    errFillAll: 'အသုံးပြုသူအမည်နှင့် စကားဝှက်ထည့်ပါ',
    errWrongCreds: 'အသုံးပြုသူအမည် သို့မဟုတ် စကားဝှက် မမှန်ကန်ပါ',
    callStaff: 'ဝန်ထမ်းခေါ်ပါ',
    tableLabel: 'စားပွဲ',
    todayMenu: 'ယနေ့မီနူး',
    menuSubtitle: "ပစ္စည်းရွေးပြီး 'အော်ဒါကြည့်' ကိုနှိပ်ပြီး တင်ပါ ☕",
    viewOrder: 'အော်ဒါကြည့်ပါ',
    tapToView: 'အော်ဒါကြည့်ရန် နှိပ်ပါ',
    myOrder: 'ကျွန်ုပ်၏ အော်ဒါ',
    total: 'စုစုပေါင်း',
    submitOrder: 'အော်ဒါတင်ပါ',
    submitting: 'တင်နေသည်...',
    orderSuccess: 'အော်ဒါ တင်ပြီးပါပြီ!',
    orderSuccessSub: 'ကျွန်ုပ်တို့ ပြင်ဆင်နေသည်\nကျေးဇူးတင်ပါသည် ☕',
    emptyCart: 'မည်သည့်ပစ္စည်းမှ မရွေးသေးပါ\nမီနူးသို့ ပြန်သွားပါ',
    soldOut: 'ကုန်သွားပြီ',
    itemNowSoldOut: '"{0}" ကုန်သွားပြီ၊ သင့် cart မှ ဖယ်လိုက်ပြီ',
    callSent: '✅ ဝန်ထမ်းကို အကြောင်းကြားပြီး၊ ကျေးဇူးပြု၍ စောင့်ပါ',
    callDuplicate: '⏳ ခေါ်ဆိုမှု ပို့ပြီး၊ ဝန်ထမ်း လာနေသည်',
    noTableHeader: 'ကြိုဆိုပါသည်',
    noTableSub: 'မီနူးကြည့်ရန် စားပွဲပေါ်ရှိ QR code ကို ဖတ်ပါ',
    noTableTitle: 'စားပွဲနံပါတ် မတွေ့ပါ',
    noTableBody: 'မီနူးကြည့်ပြီး မှာယူရန်\nသင့်စားပွဲ၏ QR code ကို ဖတ်ပါ',
    signOut: 'ထွက်ပါ',
    tablesCalling: 'စားပွဲ ခေါ်ဆိုနေသည်',
    customerCalls: '📢 ဖောက်သည် ခေါ်ဆိုနေသည်',
    orderMgmt: 'အော်ဒါ စီမံခန့်ခွဲမှု',
    lastUpdated: 'နောက်ဆုံးပြင်ဆင်ချိန်',
    autoRefresh: '၃ စက္ကန့်တိုင်း အလိုအလျောက်ပြောင်းသည်',
    pending: 'စောင့်ဆိုင်းဆဲ',
    completed: 'ပြီးဆုံးပြီ',
    tableNum: 'စားပွဲ',
    cancelOrder: 'အော်ဒါဖျက်ပါ',
    checkout: 'ငွေချေပါ',
    checkoutTitle: 'ငွေချေပါ',
    amountDue: 'ပေးဆောင်ရမည့်ငွေ',
    confirmPayment: 'ငွေပေးချေမှု အတည်ပြုပါ ✓',
    cancel: 'မလုပ်တော့ပါ',
    confirmCancelTitle: 'အော်ဒါ ဖျက်မည်လား?',
    confirmCancelMsg: 'စားပွဲ {0} ၏ အော်ဒါကို ဖျက်မည်။ ပြောင်းလဲ၍ မရပါ။',
    back: 'နောက်သို့',
    confirmCancel: 'ဖျက်မည်အတည်ပြုပါ',
    noPending: 'စောင့်ဆိုင်းဆဲ အော်ဒါ မရှိပါ',
    noCompleted: 'ယနေ့ ပြီးဆုံးသော အော်ဒါ မရှိပါ',
    toastPayment: '✅ ငွေပေးချေမှု အောင်မြင်သည်',
    toastCancelled: 'အော်ဒါ ဖျက်ပြီး',
    toastNewOrder: '🔔 အော်ဒါအသစ် +{0}',
    toastNewCall: '📢 ဖောက်သည် ဝန်ထမ်းခေါ်နေသည်',
    toastDismissed: '✅ ဖြေရှင်းပြီးအဖြစ် မှတ်သားပြီ',
    statusPaid: '✓ ငွေချေပြီ',
    statusCancelled: '✕ ဖျက်သိမ်းပြီ',
    eachUnit: '¥{0} တစ်ခွက်',
    dashTitle: 'မန်နေဂျာ ဘုတ်ဖျာ',
    menuMgmt: 'မီနူး',
    qrCodes: 'QR ကုဒ်',
    reports: 'အစီရင်ခံစာ',
    addItem: 'ပစ္စည်းထည့်ပါ',
    phItemName: 'ပစ္စည်းအမည်၊ ဥပမာ Latte',
    phItemCode: 'ကုဒ်၊ ဥပမာ C01',
    phItemPrice: 'ဈေးနှုန်း (K)',
    addBtn: 'ထည့်ပါ',
    deleteItem: 'ဖျက်ပါ',
    deleteConfirm: '"{0}" ကို ဖျက်မည်လား? ပြောင်းလဲ၍ မရပါ။',
    baseUrl: 'မီနူး URL',
    tableCount: 'စားပွဲ အရေအတွက်',
    generateQR: 'QR ကုဒ် ထုတ်ပါ',
    downloadQR: 'ဒေါင်းလုပ်',
    downloadAll: 'အားလုံးဒေါင်းလုပ်',
    tableQrLabel: 'စားပွဲ {0}',
    noItems: 'မီနူး ဗလာ ဖြစ်သည်',
    loadFailed: 'ဆွဲယူမှု မအောင်မြင်',
    toastAdded: '✅ ထည့်ပြီး',
    toastDeleted: '✅ ဖျက်ပြီး',
    toastPriceOK: '✅ ဈေးနှုန်း ပြင်ပြီး',
    toastAvailOK: '✅ အခြေအနေ ပြင်ပြီး',
    toastErrAdd: '❌ ထည့်မှု မအောင်မြင်',
    toastErrDel: '❌ ဖျက်မှု မအောင်မြင်',
    toastErrPrice: '❌ ဈေးနှုန်း ပြင်မှု မအောင်မြင်',
    toastErrAvail: '❌ အခြေအနေ ပြင်မှု မအောင်မြင်',
    itemName: 'ပစ္စည်းအမည်',
    itemCode: 'ကုဒ်',
    itemPrice: 'ဈေးနှုန်း',
    addImage: 'ပုံထည့်ရန်',
    secondsAgo: '{0} စက္ကန့်ကျော်ပြီ',
    minutesAgo: '{0} မိနစ်ကျော်ပြီ',
    hoursAgo: '{0} နာရီကျော်ပြီ',
  },
};

// ── Context ───────────────────────────────────────────────────────────────────

const LANG_KEY = 'hanaCoffeeLang';

interface LangContextValue {
  lang: string;
  setLang: (code: string) => void;
  t: (key: string, ...args: unknown[]) => string;
}

const LangContext = createContext<LangContextValue>({} as LangContextValue);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState(() => localStorage.getItem(LANG_KEY) || 'zh');

  function setLang(code: string) {
    localStorage.setItem(LANG_KEY, code);
    setLangState(code);
  }

  function t(key: string, ...args: unknown[]): string {
    let str = TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.zh?.[key] ?? key;
    args.forEach((v, i) => {
      str = str.replace(new RegExp('\\{' + i + '\\}', 'g'), String(v));
    });
    return str;
  }

  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
